# -*- coding: utf-8 -*-
"""Timeseries_Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BRPTX8qeHlsZiy1bk9rcgrplwyRHNqsX
"""

import numpy as np
import pandas as pd
from keras.layers import Dense, LSTM, Dropout, Bidirectional
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

df = pd.read_csv('AAPL.csv')
df.head(10)

target_columns = ['Date', 'Close']
df = df[target_columns]
df.head()

df.info()

data_train, data_test = train_test_split(df, test_size=0.2, random_state=69, shuffle=False)

dates = data_train['Date'].values
stock = data_train['Close'].values
dates_test = data_test['Date'].values
stock_test = data_test['Close'].values

plt.figure(figsize=(15,5))
plt.plot(df['Date'],df['Close'])
plt.title('Apple Stock Price', fontsize=20)
plt.show()

min_max_scaler = MinMaxScaler()
stock = stock.reshape(-1,1)
stock_test = stock_test.reshape(-1,1)
min_max_scaler.fit(stock)

stock = min_max_scaler.transform(stock)
stock_test = min_max_scaler.transform(stock_test)

print(stock.shape)

threshold_mae = (stock.max() - stock.min()) * 10/100
print(threshold_mae) #mae model harus lebih kecil dari ini

class BerhentiBos(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if logs.get('mae')<threshold_mae and logs.get('val_mae')<threshold_mae:
      self.model.stop_training = True

def windowed_dataset(series, window_size, batch_size, shuffle_buffer):
  ds = tf.data.Dataset.from_tensor_slices(series)
  ds = ds.window(window_size + 1, shift=1, drop_remainder=True)
  ds = ds.flat_map(lambda w: w.batch(window_size+1))
  ds = ds.shuffle(shuffle_buffer)
  ds = ds.map(lambda w: (w[:-1], w[-1:]))
  return ds.batch(batch_size).prefetch(1)

train_set = windowed_dataset(stock, window_size=50, batch_size=100,shuffle_buffer=1000)
test_set = windowed_dataset(stock_test, window_size=50, batch_size=100, shuffle_buffer=1000)
model = tf.keras.Sequential([
    Bidirectional(LSTM(32, return_sequences=True)),
    Dropout(0.5),
    Bidirectional(LSTM(32)),
    Dropout(0.5),
    Dense(16, activation="relu"),
    Dense(1)
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss=tf.keras.losses.Huber(),
    metrics=['mae']
)

berhenti_bos = BerhentiBos()
mymodel = model.fit(
    train_set,
    epochs=100,
    validation_data=test_set,
    callbacks=[berhenti_bos],
    verbose=2
)

plt.plot(mymodel.history['loss'])
plt.plot(mymodel.history['val_loss'])
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='center right')
plt.show()

plt.plot(mymodel.history['mae'])
plt.plot(mymodel.history['val_mae'])
plt.title('Model MAE')
plt.ylabel('MAE')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='center right')
plt.show()

prediction_train = model.predict(train_set)

stock = min_max_scaler.inverse_transform(stock.reshape(-1, 1))
prediction_train = min_max_scaler.inverse_transform(prediction_train.reshape(-1, 1))

plt.figure(figsize=(12,9))
plt.plot(dates, stock, label="Actual Stock")
plt.plot(dates[50:], prediction_train, label="Predicted Stock", color="C3")
plt.legend()
plt.title("Apple Stock Forecast - Train Data")
plt.xlabel("Date")
plt.ylabel("Stock Price")
plt.show()

prediction_test = model.predict(test_set)

stock_test = min_max_scaler.inverse_transform(stock_test.reshape(-1, 1))
prediction_test = min_max_scaler.inverse_transform(prediction_test.reshape(-1, 1))

plt.figure(figsize=(12,9))
plt.plot(dates_test, stock_test, label="Actual Stock")
plt.plot(dates_test[50:], prediction_test, label="Predicted Stock", color="C3")
plt.legend()
plt.title("Apple Stock Forecast - Test Data")
plt.xlabel("Date")
plt.ylabel("Stock Price")
plt.show()